### ISSUE TITLE
Having hard time to compile it

### ISSUE THREAD

**Issue by miranos** [fhissen/CrococryptFile#2]
Each time i get this error message:
```
....
parameters are invalid (no valid provider or file)");
                                                        ^
  symbol:   variable UICenter
  location: class CrococryptFile
c:\crypto\main\org\crococryptfile\CrococryptFile.java:222: error: cannot find sy
mbol
                                                UICenter.message("Input paramete
rs are invalid");
                                                ^
  symbol:   variable UICenter
  location: class CrococryptFile
c:\crypto\main\org\crococryptfile\CrococryptFile.java:227: error: cannot find sy
mbol
                                if(UICenter.isGUI()){
                                   ^
  symbol:   variable UICenter
  location: class CrococryptFile
100 errors
```

Tried to compile it with this command line:
`javac -bootclasspath CrococryptFile/lib/bc.jar;CrococryptFile/lib/bcpg.jar;CrococryptFile/lib/commonsc.jar -classpath . CrococryptFile/main/org/crococryptfile/CrococryptFile.java`

And too with this one:
`C:\crypto>javac -cp "c:\crypto\lib\*" c:\crypto\main\org\crococryptfile\CrococryptFile.java`

I am under `Windows 7 x64`.

JAVA:

```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

Please help to solve this issue  and compile it !

**Comment by fhissen** [comment]
This works for me:

`javac -cp common;main;lib\bc.jar;lib\bcpg.jar;lib\commonsc.jar main\org\crococryptfile\CrococryptFile.java`

**Comment by miranos** [comment]
It worked fine, i used this command:
`javac -d ./build -cp common;main;lib\bc.jar;lib\bcpg.jar;lib\commonsc.jar main\org\crococryptfile\CrococryptFile.java`

And then i wanted to convert it to JAR file with this command:
`jar cvf CrococryptFile.jar *`

When i launch it: java -jar CrococryptFile.jar i got this error message:
`no main manifest attribute, in CrococryptFile.jar`

**Comment by fhissen** [comment]
Please look for a Java basics tutorial, this is no forum!
